### ISSUE TITLE
Map is not displaying completely

### ISSUE THREAD

**Issue by HydRen-fr** [shubhexists/react-maps#10]
Hello, 

My map is not displaying completely as you've mentioned it in the disclaimer.
I've coded my app on CodeSandbox and I use Firefox.
If it helps, you can see the code of my project here : https://github.com/HydRen-fr/Flora.
I've also put the app online already to see if it would solve the problem, but it doesn't : https://flora-qwia.onrender.com.

Thanks a lot for your project anyway, it's great !

**Comment by shubhexists** [comment]
@HydRen-fr Hey, I have checked and it is a viewport issue.
Thanks for reporting. I'll fix it and let you know.
Thanks again..

**Comment by HydRen-fr** [comment]
Thank you ! It works perfectly now.
