### ISSUE TITLE
Adding Support for Labels in Map Library

### ISSUE THREAD

**Issue by altughan09** [shubhexists/react-maps#3]
**Problem:**

- The current version of the map library lacks support for displaying labels on the map, which limits its usability in various applications. Labels are essential for providing context and information about specific geographic locations or regions.

**Proposed Solution:**

- To enhance the functionality and usability of the map library, it would be beneficial to add support for displaying labels on the map. This feature would allow users to add text labels to specific points or regions on the map, providing additional information and context.

**Expected Behavior:**

- Users should be able to specify the text content of the label.
- Labels should be positioned accurately relative to the specified geographic location.
- Labels should support customization options such as font size, color, and style.
- Labels should be responsive to changes in the map's zoom level and viewport size.

**Comment by shubhexists** [comment]
Hi @altughan09 , I needed some clarification on what do you mean by labels 
Is it something like this? Each subportion (region) has a label associated to it?
![map](https://github.com/shubhexists/react-maps/assets/110319892/d16e19c9-0a36-4042-957a-6d4522dd66ee)

**Comment by altughan09** [comment]
Hi @shubhexists, yes, would be nice to have something where user is able to place text inside the region/country/continent defined by coordinates. Also would be great to have another version of the world map that displays continents only (without country borders). But I can imagine this would require some effort and time.

**Comment by shubhexists** [comment]
Got it.
As far as continents is concerned.. 
There is already a package for that...
https://www.npmjs.com/package/@react-map/continents

**Comment by altughan09** [comment]
Thank you @shubhexists, will take a look.

**Comment by shubhexists** [comment]
Hi @altughan09 , wanted your reviews on this a bit - 
Does something like this solve the issue? What else could be added etc etc...
Also apologies for the delay. I got a bit short on time : )

[Screencast from 03-04-24 06:39:51 PM IST.webm](https://github.com/shubhexists/react-maps/assets/110319892/43624533-078d-40a3-8419-1dc63e87651a)

**Comment by shubhexists** [comment]
This issue is now solved in the latest versions of all the packages by PR #4 ...
