### ISSUE TITLE
hover and select of path just assigned to the last components u call 

### ISSUE THREAD

**Issue by solish82** [shubhexists/react-maps#8]
import Iran from "@react-map/iran";

export default function Map() {
  return (
 /<Iranmap Color='white' hoverColor='#0E8B09' type='select-single' strokeColor='#666666' //>
  );
}

index.js
import Map from ./map

export default function Index () {
[1, 2].map(() => {
return /<Map //>
})
}

**Comment by shubhexists** [comment]
Hey, can you please explain the issue in brief what are you facing?

**Comment by shubhexists** [comment]
Closing this as no response. You may open this issue if you need assistance
