### ISSUE TITLE
After version 1.0.3 the map disappeared from App

### ISSUE THREAD

**Issue by thiagoloureiro** [shubhexists/react-maps#9]
I am currently using "@react-map/continents": "1.0.2

After trying to upgrade to 1.0.3 or 1.0.4 

![image](https://github.com/user-attachments/assets/6eacffb5-41c8-4c10-a96d-61e5abbfc114)

any thoughts?

my repo:
https://github.com/thiagoloureiro/AlertHawk.ui

**Comment by shubhexists** [comment]
Also, apologies for the delay in response and updation...

**Comment by thiagoloureiro** [comment]
No worries! We will try here and update you back. Thanks a lot!Sent from my iPhoneOn 26 Jul 2024, at 14:27, Shubham ***@***.***> wrote:﻿
Also, apologies for the delay in response and updation...

**Comment by thiagoloureiro** [comment]
Fixed:)
https://github.com/thiagoloureiro/AlertHawk.UI/commit/970bd3d2276ddfdd30431b023aea95eac0be3018

thank you!
